"""company init — first-time setup."""

import sys
from datetime import date
from pathlib import Path

from lib.helpers import (
    BASE_DIR, CONFIG_FILE, save_config, prompt, prompt_choice,
    validate_slug, ensure_dir, expand_path
)
from lib.journal import (
    ensure_year_structure, write_journal_atomic, INCLUDE_DIR, GENERATED_DIR,
    JOURNAL_DIR
)


def cmd_init():
    """First-time setup for hledger-company."""
    if CONFIG_FILE.exists():
        print("config.yaml already exists.")
        print("Use 'company generate' to regenerate journals.")
        return

    print("company — First Time Setup\n")

    # Company identity
    company_name = prompt("Company name")
    slug = prompt("Entity slug (short identifier)", validator=validate_slug)
    currency = prompt("Default currency", default="CAD")
    journal_file = prompt("Main hledger journal file", default="~/.hledger.journal")

    # Primary bank account
    bank_name = prompt("Primary bank account name", default="Chequing")
    bank_account = f"Assets:Current:{bank_name}"

    # Fiscal year
    current_year = date.today().year
    fiscal_start = prompt("Fiscal year start month (1-12)", default="1")

    # Divisions
    divisions_raw = prompt("Divisions (optional, comma-separated, or blank for none)",
                           required=False)
    divisions = [d.strip() for d in divisions_raw.split(',') if d.strip()] if divisions_raw else []

    # Create config
    config = {
        'company': {
            'name': company_name,
            'slug': slug,
            'currency': currency,
        },
        'journal_file': journal_file,
        'accounts': {
            'bank': bank_account,
            'receivable': 'Assets:Current:Accounts Receivable',
            'payable': 'Liabilities:Current:Accounts Payable',
        },
        'divisions': divisions,
        'defaults': {
            'fiscal_year_start': int(fiscal_start),
        }
    }
    save_config(config)
    print(f"\n  Created config.yaml")

    # Create directory structure
    for d in ['assets', 'liabilities', 'contacts', 'contracts', 'projects',
              'invoices', 'templates', 'output', 'build', 'timesheets',
              'timesheets/billed']:
        ensure_dir(BASE_DIR / d)

    # Set up the include chain for current year
    ensure_year_structure(current_year)

    # Create accounts.journal
    accounts_journal = INCLUDE_DIR / "accounts.journal"
    write_journal_atomic(accounts_journal, _default_accounts(bank_account, currency))
    print(f"  Created include/accounts.journal")

    # Create or update the main journal file
    journal_path = expand_path(journal_file)
    include_line = f"include {BASE_DIR}/include/company.journal\n"

    if not journal_path.exists():
        # Create it with the include line
        journal_path.parent.mkdir(parents=True, exist_ok=True)
        with open(journal_path, 'w') as f:
            f.write(f"; {company_name} — main ledger\n")
            f.write(f"; Created by: company init\n\n")
            f.write(include_line)
        print(f"\n  Created {journal_file} with include line.")
    else:
        # Check if include already exists
        content = journal_path.read_text()
        if str(BASE_DIR / "include" / "company.journal") not in content:
            print(f"\n  Add this line to {journal_file}:")
            print(f"    {include_line.strip()}")
        else:
            print(f"\n  {journal_file} already includes company.journal.")

    # Summary
    print(f"  Directory structure created.")
    print(f"  Include chain ready at: include/company.journal")
    print(f"\n  You're ready. Try 'company asset add' or 'company worth'.")


def _default_accounts(bank_account, currency):
    """Generate default accounts.journal content."""
    return """; hledger-company account declarations
; Generated by: company init

; Assets — Current
account Assets:Current:Chequing                              ; type:A
account Assets:Current:Savings                               ; type:A
account Assets:Current:Petty Cash                            ; type:A
account Assets:Current:Accounts Receivable                   ; type:A
account Assets:Current:Prepaid Expenses                      ; type:A

; Assets — Fixed
account Assets:Fixed:Equipment                               ; type:A
account Assets:Fixed:Vehicles                                ; type:A
account Assets:Fixed:Furniture                               ; type:A
account Assets:Fixed:Leasehold Improvements                  ; type:A
account Assets:Fixed:Intellectual Property                   ; type:A

; Assets — Accumulated Amortization (contra)
account Assets:Accumulated Amortization:Equipment            ; type:A
account Assets:Accumulated Amortization:Vehicles             ; type:A
account Assets:Accumulated Amortization:Furniture            ; type:A
account Assets:Accumulated Amortization:Leasehold Improvements ; type:A
account Assets:Accumulated Amortization:Intellectual Property ; type:A

; Liabilities — Current
account Liabilities:Current:Accounts Payable                 ; type:L
account Liabilities:Current:Credit Card                      ; type:L
account Liabilities:Current:HST Payable                      ; type:L
account Liabilities:Current:Payroll Payable                  ; type:L
account Liabilities:Current:Income Tax Payable               ; type:L
account Liabilities:Current:Unearned Revenue                 ; type:L

; Liabilities — Long-Term
account Liabilities:Long-Term:Bank Loan                      ; type:L
account Liabilities:Long-Term:Vehicle Loan                   ; type:L
account Liabilities:Long-Term:Shareholder Loan               ; type:L

; Equity
account Equity:Owner Investment                              ; type:E
account Equity:Owner Draws                                   ; type:E
account Equity:Retained Earnings                             ; type:E

; Income — Operating
account Income:Operating:Consulting                          ; type:R
account Income:Operating:Services                            ; type:R
account Income:Operating:Product Sales                       ; type:R
account Income:Operating:Recurring Revenue                   ; type:R

; Income — Non-Operating
account Income:Non-Operating:Interest Income                 ; type:R
account Income:Non-Operating:Gain on Disposal                ; type:R
account Income:Non-Operating:Foreign Exchange Gain           ; type:R
account Income:Non-Operating:Other Income                    ; type:R

; Expenses — Operating
account Expenses:Operating:Payroll:Salaries                  ; type:X
account Expenses:Operating:Payroll:Benefits                  ; type:X
account Expenses:Operating:Payroll:Employer Contributions    ; type:X
account Expenses:Operating:Rent                              ; type:X
account Expenses:Operating:Utilities                         ; type:X
account Expenses:Operating:Insurance                         ; type:X
account Expenses:Operating:Office Supplies                   ; type:X
account Expenses:Operating:Software Subscriptions            ; type:X
account Expenses:Operating:Professional Fees                 ; type:X
account Expenses:Operating:Travel                            ; type:X
account Expenses:Operating:Meals and Entertainment           ; type:X
account Expenses:Operating:Marketing                         ; type:X
account Expenses:Operating:Telecommunications               ; type:X
account Expenses:Operating:Bank Fees                         ; type:X
account Expenses:Operating:Repairs and Maintenance           ; type:X

; Expenses — Non-Operating
account Expenses:Non-Operating:Amortization                  ; type:X
account Expenses:Non-Operating:Interest Expense              ; type:X
account Expenses:Non-Operating:Loss on Disposal              ; type:X
account Expenses:Non-Operating:Foreign Exchange Loss         ; type:X
account Expenses:Non-Operating:Income Tax Expense            ; type:X
"""
